import type { Metadata } from 'next';
import localFont from 'next/font/local';
import '../globals.css';
import MaterialThemeProvider from '@/providers/MaterialThemeProvider';
import ReduxProvider from '@/providers/ReduxProvider';
import SnackBarProvider from '@/providers/SnackbarProvider';

const helveticaBold = localFont({
  src: '../../fonts/Helvetica-Bold.ttf',
  variable: '--font-geist-sans',
  weight: '400 700',
});

export const metadata: Metadata = {
  title: 'Universal',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${helveticaBold.variable} antialiased`}>
        <div className="w-screen bg-black h-screen">
          <MaterialThemeProvider>
            <ReduxProvider>
              <SnackBarProvider>{children}</SnackBarProvider>
            </ReduxProvider>
          </MaterialThemeProvider>
        </div>
      </body>
    </html>
  );
}
