import type { Metadata } from 'next';
import localFont from 'next/font/local';
import '../globals.css';
import AuthProviders from './AuthProviders';

const helveticaBold = localFont({
  src: '../../fonts/Helvetica-Bold.ttf',
  variable: '--font-geist-sans',
  weight: '400 700',
});

export const metadata: Metadata = {
  title: 'Universal',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${helveticaBold.variable} antialiased overflow-hidden`}>
        <div className="w-screen bg-Black h-screen">
          <AuthProviders>{children}</AuthProviders>
        </div>
      </body>
    </html>
  );
}
