export const STRINGS = {
  dashboard: 'Dashboard',
  employeeManagement: 'Employee Management',
  clientManagement: 'Client Management',
  subAdminManagement: 'Sub-admin Management',
  company: 'Company',
  activityLog: 'Activity Logs',
  settings: 'Settings',
  pleaseEnterYour:
    'Please enter your credentials to access the admin dashboard',
  profile: 'Profile',
  logout: 'Logout',
  login: 'Login',
  email: 'Email',
  password: 'Password',
  signUp: 'Sign Up',
  something_went_wrong: 'OOPS!! Something went wrong. please try again later',
  logout_message: 'Are you sure you want to logout this account?',
  all: 'All',
  pending: 'Pending',
  addSubAdmin: 'Add Sub-admin',
  addEmployee: 'Add Employee',
  updateSubAdmin: 'update SubAdmin',
  approved: 'Approved',
  deny: 'Deny',
  declined: 'Declined',
  fullTime: 'Full Time',
  partTime: 'Part Time',
  addNewSubAdmin: 'Add New Sub-admin',
  addNewCompany: 'Add New Company',
  firstName: 'First Name',
  lastName: 'Last Name',
  name: 'Name',
  contactNumber: 'Contact Number',
  status: 'Status',
  firstNameKey: 'firstName',
  firstNameKeyError: 'firstNameError',
  lastNameKeyError: 'lastNameError',
  lastNameKey: 'lastName',
  noSubAdmin: 'No Sub-Admin Added Yet',
  noSubAdminDec: 'Click the add sub admin button to assign new sub admin',
  active: 'Active',
  inActive: 'InActive',
  create: 'Create',
  update: 'Update',
  subAdminAdded: 'Sub-Admin Added Successfully!',
  noUpdate: 'No Field Updated!!',
  subAdminUpdated: 'Sub-Admin updated Successfully!',
  documentStatus: 'Document Status',
  workStatus: 'Work Status',
  noEmployees: 'No Employees Available',
  addCompany: 'Add Company',
  uploadProfile: 'Upload Profile',
  personalInformation: 'Personal Information',
  companyName: 'Company Name',
  accountRequestName: 'Account request name',
  address: 'Address',
  otherInformation: 'Other Information',
  companyRegisteredNumber: 'Company registered number',
  gstHSTNumber: 'GST/HST number',
  websiteLink: 'Website link',
  industry: 'Industry',
  your_internet_is_a_little_wonky_right_now:
    'Your internet is a little wonky right now. Please try switching to other networks',
  required_field: 'This is required field',
  valid_email: 'Please enter a valid email',
  valid_phone_number: 'Please enter a valid phone number',
};
