export const STRINGS = {
  dashboard: 'Dashboard',
  employeeManagement: 'Employee Management',
  clientManagement: 'Client Management',
  subAdminManagement: 'Sub-admin Management',
  company: 'Company',
  activityLog: 'Activity Logs',
  settings: 'Settings',
  pleaseEnterYour:
    'Please enter your credentials to access the admin dashboard',
  profile: 'Profile',
  logout: 'Logout',
  login: 'Login',
  email: 'Email',
  password: 'Password',
  signUp: 'Sign Up',
  something_went_wrong: 'OOPS!! Something went wrong',
  logout_message: 'Are you sure you want to logout this account?',
  all: 'All',
  pending: 'Pending',
  addSubAdmin: 'Add Sub-admin',
  addEmployee: 'Add Employee',
  updateSubAdmin: 'Update SubAdmin',
  approved: 'Approved',
  deny: 'Deny',
  declined: 'Declined',
  fullTime: 'Full Time',
  partTime: 'Part Time',
  addNewSubAdmin: 'Add New Sub-admin',
  addNewCompany: 'Add New Company',
  firstName: 'First Name',
  lastName: 'Last Name',
  name: 'Name',
  contactNumber: 'Contact Number',
  status: 'Status',
  firstNameKey: 'firstName',
  firstNameKeyError: 'firstNameError',
  lastNameKeyError: 'lastNameError',
  lastNameKey: 'lastName',
  noSubAdmin: 'No Sub-Admin Added Yet',
  noClients: 'No Clients Added Yet',
  noJobs: 'No Jobs Added Yet',
  noJobsCompleted: 'No Jobs Completed Yet',
  noClientDec: 'Click the add client button to add a new client',
  noSubAdminDec: 'Click the add sub admin button to assign new sub admin',
  active: 'Active',
  inActive: 'InActive',
  create: 'Create',
  update: 'Update',
  saveChanges: 'Save changes',
  subAdminAdded: 'Sub-Admin Added Successfully!',
  noUpdate: 'No Field Updated!!',
  subAdminUpdated: 'Sub-Admin updated Successfully!',
  documentStatus: 'Document Status',
  workStatus: 'Work Status',
  noEmployees: 'No Employees Available',
  addCompany: 'Add Company',
  uploadProfile: 'Upload Profile',
  personalInformation: 'Personal Information',
  companyName: 'Company Name',
  accountRequestName: 'Account request name',
  address: 'Address',
  otherInformation: 'Other Information',
  companyRegisteredNumber: 'Company registered number',
  coRegisteredNumber: 'Co. Registered Number',
  gstHSTNumber: 'GST/HST Number',
  websiteLink: 'Website link',
  industry: 'Industry',
  your_internet_is_a_little_wonky_right_now:
    'Your internet is a little wonky right now. Please try switching to other networks',
  required_field: 'This is required field',
  valid_email: 'Please enter a valid email',
  valid_phone_number: 'Please enter a valid phone number',
  view: 'View',
  applied: 'Applied',
  completed: 'Completed',
  event: 'Event',
  post_ID: 'Post ID',
  reqcandidate: 'Required candidates',
  yoe: 'Years of Experience',
  gender: 'Gender',
  male: 'Male',
  female: 'Female',
  jobName: "Job Name",
  jobDes: 'Job Description',
  jobDut: 'Job Duties',
  reqCert: 'Required Certificate',
  pendingReq: 'Pending Request',
  selectComp: 'Select the company',
  addClient: 'Add Client',
  joiningDate: 'Join Date',
  clientNameAndComp: 'Client Name & Company',
  contactDetails: 'Contact Details',
  location: 'Location',
  action: 'Action',
  no_pending: 'No pending request',
  date: 'Date',
  verify: 'Verify',
  verified: 'Verified',
  verifiedClient: 'You have successfully verified the new client request',
  confirm: 'Confirm',
  no_companies: 'No Companies Found',
  clientName: 'Client Name',
  clientAdded: 'Client added successfully!!',
  clientCreated: 'Client created successfully!!',
  allClient: 'All Clients',
  openJob: 'Open jobs',
  closeJob: 'Closed jobs',
  notAccept: 'Not accepting',
  viewCheckin: 'View checkin report',
  shiftTime: 'Shift time',
  wageRate: 'Wages rate',
  jobType: 'Job type',
  noOpenJob: 'Company not available open job',
  noClosedJob: 'Company not available close job',
  noClient: 'Company not available any client',
  clientAddress: 'Client address',
  postJobs: 'Posted Jobs',
  sinDocument: 'Sin document',
  Govt_ID: 'Govt. IDs',
  directDeposit: 'directDepositVoidCheque',
  document: 'Document (PR card, Permit)',
  license_advance: 'Security license advance',
  license_basic: 'Security license basic',
  bankDetails: 'Bank Details',
  profileHistory: 'Profile History',
  mandatoryDoc: 'Mandatory documents',
  otherDoc: 'Other documents',
  checkin: 'Checkin',
  checkout: 'Checkout',
  noRequestFound: 'No Requests Found',
  youHaveNoPending: 'You have no pending document requests at this time',
  eventDate: 'Event date',
  startShift: 'Start shift',
  endShift: 'End shift',
  num_of_employees: 'Number of employees needed',
  wagePerHour: 'Wages/hr',
  pay_schedule: 'Payment schedule',
  postalCode: 'Postal Code',
  city: 'City',
  cheque: 'Direct deposit/ void cheque',
  saveChange: 'Save Changes',
  myacc: 'My Account',
  faq: 'FAQs',
  addFaq: 'Add FAQs',
  faqs: 'Frequently Asked Questions',
  notification: 'Notification',
  edit: 'Edit',
  save: 'Save',
  delete: 'Delete',
  delete_message: 'Are you sure you want to delete this question?',
  details: 'Details',
  general: 'General',
  requirement: 'Requirement',
  updateRequest: 'Update Request',
  previousDoc: 'Previous Document',
  updatedDoc: 'Updated Document',
  advance: 'Advance-',
  basic: 'Basic-',

  close: 'Close',
  closed: 'Closed',
  open: 'Open',
  help: 'Help & Support',
  noIssue: 'NoIssue',
  activity: 'Activity',
  recentAct: 'Recent Activity',
  daily: 'Daily',
  weekly: 'Weekly',
  monthly: 'Monthly',
  yearly: 'Yearly',
  jobPosting: 'Job Posting',
  newClient: 'New Client',
  newEmp: 'New Employee',
  compareWeek: 'Compare to last week',
  noHelp: "No Issues Raised Yet",
  jobStatus: 'Job Status'
};
