import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import Sidebar from '@/components/organism/Sidebar';

const helveticaBold = localFont({
  src: '../fonts/Helvetica-Bold.ttf',
  variable: '--font-geist-sans',
  weight: '400 700',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${helveticaBold.variable} antialiased`}>
        <div className="flex bg-primary h-screen flex-row">
          <div className="w-[19.33%]">
            <Sidebar />
          </div>
          <div className="w-[80.77%] rounded-l-[40px] bg-white">{children}</div>
        </div>
      </body>
    </html>
  );
}
