import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Sidebar from "@/components/organism/Sidebar";
import Topbar from "@/components/organism/Topbar";

const helveticaBold = localFont({
  src: "../fonts/Helvetica-Bold.ttf",
  variable: "--font-geist-sans",
  weight: "400 700",
});

export const metadata: Metadata = {
  title: "Universal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${helveticaBold.variable} antialiased`}>
        <div className="flex bg-primary  flex-row">
          <div className="w-[19.33%]">
            <Sidebar />
          </div>
          <div className="w-[80.77%] rounded-l-[40px] bg-white">
            <Topbar/>
            {children}</div>
        </div>
      </body>
    </html>
  );
}
