import type { Metadata } from 'next';
import localFont from 'next/font/local';
import '../globals.css';
import Sidebar from '@/components/organism/Sidebar/Sidebar';

import Topbar from '@/components/organism/Topbar/Topbar';
import HomeProviders from './HomeProviders';

const helveticaBold = localFont({
  src: '../../fonts/Helvetica-Bold.ttf',
  variable: '--font-geist-sans',
  weight: '400 700',
});

export const metadata: Metadata = {
  title: 'Universal',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${helveticaBold.variable} antialiased`}>
        <HomeProviders>
          <div className="flex flex-row">
            <div className="h-screen w-[25%] max-w-[280px] bg-black">
              <Sidebar />
            </div>
            <div className=" w-screen bg-black overflow-hidden flex flex-row justify-center">
              <div className="max-w-screen-2xl h-screen w-full">
                <div className="w-full h-full rounded-l-[40px] overflow-hidden">
                  <Topbar />
                  <div className="bg-extraWhite rounded-bl-lg h-[90%] w-full overflow-scroll px-10 pb-4 scrollbar-none">
                    {children}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </HomeProviders>
      </body>
    </html>
  );
}
