import type { Metadata } from 'next';
import localFont from 'next/font/local';
import '../globals.css';
import Sidebar from '@/components/organism/Sidebar/Sidebar';

import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import MaterialThemeProvider from '@/providers/MaterialThemeProvider';
import ReduxProvider from '@/providers/ReduxProvider';
import SnackBarProvider from '@/providers/SnackbarProvider';
import Topbar from '@/components/organism/Topbar/Topbar';

const helveticaBold = localFont({
  src: '../../fonts/Helvetica-Bold.ttf',
  variable: '--font-geist-sans',
  weight: '400 700',
});

export const metadata: Metadata = {
  title: 'Universal',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${helveticaBold.variable} antialiased`}>
        <AppRouterCacheProvider>
          <MaterialThemeProvider>
            <SnackBarProvider>
              <ReduxProvider>
                <div className="flex flex-row">
                  <div className="h-screen w-[25%] max-w-[280px] bg-black">
                    <Sidebar />
                  </div>
                  <div className=" w-screen bg-black overflow-hidden flex flex-row justify-center">
                    <div className="max-w-screen-2xl h-screen w-full">
                      <div className="w-full h-full rounded-l-[40px] overflow-hidden">
                        <Topbar />
                        <div className="bg-extraWhite rounded-bl-lg overflow-scroll px-10 pb-10">
                          {children}
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </ReduxProvider>
            </SnackBarProvider>
          </MaterialThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
